name: dl4nlp
channels:
  - defaults
  - pytorch
  - anaconda
  - conda-forge
dependencies:
  - python==3.11.9
  - numpy==1.25.2
  - pandas
  - transformers
  - pytorch
  - lightning==2.2.1
  - tqdm=4.66.1
  - pip
  - pip:
    - lingua-language-detector
    - wget