#!/bin/bash

#SBATCH --partition=gpu_h100
#SBATCH --gpus=4
#SBATCH --job-name=DetectGPTTest
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=18
#SBATCH --time=4:00:00
#SBATCH --output=outputs/dgpt_test_%A.out

module purge
module load 2023
module load Anaconda3/2023.07-2

cd $HOME/DL4NLP/ # Change with where you want the file to be if desired
target_f=$HOME/DL4NLP/

source activate dl4nlp_gpu
# Adjust AI location to where the AI files are located
srun python -u main.py \
    --save_dir $target_f \
    --ai_location "mistral" \