#!/bin/bash

#SBATCH --partition=gpu_h100
#SBATCH --gpus=2
#SBATCH --job-name=QwenGenerate
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=18
#SBATCH --time=5:00:00
#SBATCH --output=outputs/qwen_%A.out

module purge
module load 2023
module load Anaconda3/2023.07-2

cd $HOME/DL4NLP/ # Change with where you want the file to be if desired
target_f=$HOME/DL4NLP/

source activate dl4nlp_gpu
srun python -u datasetGenerationQwen.py \
    --model_id "Qwen/Qwen2.5-32B-Instruct" \
    --device "cuda" \
    --languages "en" "id" "zh" "de" "ru" \
    --target_folder $target_f